spring.application.name=CadastroDeNinjas
server.port=8081

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true

# Define o caminho para acessar o console
spring.h2.console.path=/h2-console


# Cria a URL de conexão do banco
spring.datasource.url=${DATABASE_URL}


# Define o usuário padrão
spring.datasource.username=${DATABASE_USERNAME}

# Deixa a senha vazia (padrão do H2)
spring.datasource.password=${DATABASE_PASSWORD}


# Define o driver correto para o H2
spring.datasource.driverClassName=org.h2.Driver

# CONFIGURAÇÕES DO JPA /HIBERNATES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true